...

diff --git a/rtd-mc b/rtd-mc
--- a/rtd-mc
+++ b/rtd-mc
@@ -50,39 +50,28 @@ COMPLETION_MESSAGE="Your ISO image is ready! It is placed in the folder: $PUT_IS
 #
 
 function prepare_environment_for_iso_creation () {
-    # Facilitate showing collorfull statements in terminal... 
-    set_colors
-    #Include the path to where the isofile will be put... 
-    TARGET_ISO="$PUT_ISO_FILE_HERE_WHEN_DONE/$TARGET_ISO_FILE_NAME"
-    # Ensure that all needed software, outside of the most rudimantary, 
-    # is available to us... If not, the script should exit. 
-    _DEPENDENCIES="dos2unix cpio gzip genisoimage whois pwgen wget fakeroot xorriso"
-    #set -e
-    for i in $_DEPENDENCIES 
-    do 
-        check_dependencies $i
-    done
+	TARGET_ISO="$PUT_ISO_FILE_HERE_WHEN_DONE/$TARGET_ISO_FILE_NAME"
+	_DEPENDENCIES="dos2unix cpio gzip genisoimage whois pwgen wget fakeroot xorriso"
 
-    # Find full paths for the binaries needed since if they are recently 
-    # added, they may not be found in the current $PATH
-    : "${BIN_7Z:=$(type -P 7z)}"
-    : "${BIN_XORRISO:=$(type -P xorriso)}"
-    : "${BIN_CPIO:=$(type -P gnucpio || type -P cpio)}"
+	for i in $_DEPENDENCIES 
+	do 
+		check_dependencies $i
+	done
 
-    # find the location of the public key on this machine...
-    # This should be updated to create a key if not there... 
-    if [ ! -f "$SSH_PUBLIC_KEY_FILE" ];
-    then
-        echo "Error: public SSH key $SSH_PUBLIC_KEY_FILE not found!"
-        # exit 1
-    fi
+	: "${BIN_7Z:=$(type -P 7z)}"
+	: "${BIN_XORRISO:=$(type -P xorriso)}"
+	: "${BIN_CPIO:=$(type -P gnucpio || type -P cpio)}"
 
-    # Setup the required folder structure... 
-    CURRENT_DIR="$(pwd)"
-    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-    TMP_DOWNLOAD_DIR="$(mktemp -d)"
-    TMP_DISC_DIR="$(mktemp -d)"
-    TMP_INITRD_DIR="$(mktemp -d)"
+	if [ ! -f "$SSH_PUBLIC_KEY_FILE" ];
+	then
+		echo "Error: public SSH key $SSH_PUBLIC_KEY_FILE not found!"
+	fi
+
+	CURRENT_DIR="$(pwd)"
+	SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+	TMP_DOWNLOAD_DIR="$(mktemp -d)"
+	TMP_DISC_DIR="$(mktemp -d)"
+	TMP_INITRD_DIR="$(mktemp -d)"
 }
 
 
@@ -101,7 +90,7 @@ function check_dependencies (){
 		then
 			echo "That install didn't work out so well."
 			echo "Please manually try to add the software since I couldn't do it."
-			exit 1
+			read -p "Press any key to EXIT" ; exit 1
 		fi
 		echo "OK Done! Continuing..."
 	fi
